#!/bin/bash
#

source $HOME/bin/vim/revision-helpers

ROOT="`dirname "$0"`"
ROOT="`cd "$ROOT" && pwd`"
COMMAND="$1"
test "$COMMAND" || exit 1
shift
DIR="`dirname "$1"`"
NAME="`basename "$1"`"
shift

cd "$DIR" || exit 1
DIR="`pwd`"

MODE="`find_revision_control "$DIR"`"

call_revision_cmd "$@"

