#!/bin/bash
#

FILENAME="${1}"
PATHNAME="${2}"

test -x $HOME/bin/show_gate_name && {
    $HOME/bin/show_gate_name "$FILENAME" "$PATHNAME"
    exit
}

echo __"$FILENAME"_INCLUDED__ | tr "[a-z]+\\\\-\\\\~\\\\.,:;/" "[A-Z]________"

