#!/bin/bash
#

for dir in . $HOME/bin
do
    test -x $dir/show_gate_name && {
        $dir/show_gate_name "$@"
        exit
    }
done

echo __"$1"_INCLUDED__ | tr "[a-z]+\\-\\~\\.,:;/" "[A-Z]________"

