#!/bin/bash
#

FILENAME="${1}"
PATHNAME="${2}"

for dir in . $HOME/bin
do
    test -x $dir/show_gate_name && {
        $dir/show_gate_name "$FILENAME" "$PATHNAME"
        exit
    }
done

echo __"$FILENAME"_INCLUDED__ | tr "[a-z]+\\\\-\\\\~\\\\.,:;/" "[A-Z]________"

