#!/bin/bash
#

function check_info()
{
    local path="${1}"
    local parent="$(dirname "$path")"
    test "$parent" != "$HOME" && test "$parent" != "/" && check_info "$parent"
    test -e "$path/project-info" && . "$path/project-info"
}

check_info "$(pwd)"

test "$COPYING" || COPYING="COPYING"
test "$LICENCE" && LICENSE="$LICENCE"
test "$LICENSE" || LICENSE="GPL (see file '$COPYING' in the project root for more details)"

cat <<EOF
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Project:     $PROJECT
 * Purpose:     $PURPOSE
 * Author:      $AUTHOR
 * License:     $LICENSE
 * Comments:    $COMMENT
 *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

EOF
