#!/bin/sh
#

test -x ./project-info && . ./project-info

test "$COPYING" || COPYING="COPYING"

cat <<EOF
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Project:     $PROJECT
 * Purpose:     $PURPOSE
 * Author:      $AUTHOR
 * Licence:     GPL (see file '$COPYING' in the project root for more details)
 * Comments:    $COMMENT
 *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

EOF
