#!/bin/sh
#

test -x $HOME/project-info && . $HOME/project-info
test -x ./project-info && . ./project-info

test "$COPYING" || COPYING="COPYING"
test "$LICENCE" || LICENCE="GPL (see file '$COPYING' in the project root for more details)"

cat <<EOF
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Project:     $PROJECT
 * Purpose:     $PURPOSE
 * Author:      $AUTHOR
 * Licence:     $LICENCE
 * Comments:    $COMMENT
 *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

EOF
