#!/bin/bash
#

GIT="`which git 2>/dev/null`"
SED="`which sed 2>/dev/null`"

. `dirname $0`/params-parse

function git_path_correct()
{
    $SED -e "s%^--- a/%--- ./%" -e "s%+++ b/%+++ ./%"
}

case "$COMMAND" in
    blame)
        $GIT blame $REVISION -- "$NAME"
    ;;
    log)
        $GIT log -n 1 $REVISION -- "$NAME"
    ;;
    change)
        $GIT diff $REVISION -- "$NAME" | git_path_correct
    ;;
    local)
        $GIT diff "$NAME" | git_path_correct
    ;;
    cat)
        $GIT show "$REVISION:./$NAME"
    ;;
    revert)
        echo "Warning: this operation is irreversible!" >&2
        read -p "Do you want to revert it (yes/no)? " yesno
        test "$yesno" = "yes" || exit 1
        $GIT checkout -- "$NAME"
    ;;
    *)
        echo "GIT: Unhandled mode: '$COMMAND'"
        exit 1
    ;;
esac
