#!/bin/bash
#

POS="$1"
RANGE="$4"

START="`echo "$RANGE" | sed "s/[+-]//g" | cut -d "," -f 1`"
LENGTH="`echo "$RANGE" | sed "s/[+-]//g" | cut -d "," -f 2`"
END=$(($START+$LENGTH))

test $POS -lt $START && exit 0
test $POS -gt $END && exit 0

DIFI=$(($POS-$START+1))

echo -n "${DIFI}"
