#!/bin/bash
#

NAME="$1"

current_dir="`pwd`/"

declare -a words=(`echo "$NAME" | tr "+\\-\\~\\.,:;/" "_______ "`)

function check_path()
{
    if test -d "${actual_path}.svn" -o -d "${actual_path}.git"
    then
        start=$index
    else
        if test "${actual_path}" = "$current_dir"
        then
            start=$index
        fi
    fi
}

if test "${NAME:0:1}" = "/"; then
    actual_path=/
else
    actual_path=
fi

start=
index=0
check_path
while test "${words[$index]}"
do
    actual_path="$actual_path${words[$index]}/"
    check_path
    index=$(($index+1))
done

echo -n "_"

if test "$start"
then
    while test $start -lt ${#words[*]}
    do
        echo -n "_${words[$start]}" | tr "[a-z]" "[A-Z]"
        start=$(($start+1))
    done
fi

echo "_INCLUDED__"

