#!/bin/bash
#

SVN="`which svn`"

. `dirname $0`/params-parse

function set_svn_root()
{
 local name="."
 test "$NAME" && name="$NAME"
 local info="`$SVN info "$name" $R_REV 2>/dev/null`"
 ORIGINAL_REVISION="`echo "$info" | grep "^Revision: " | cut -d " " -f 2`"
 SVN_PATH="`echo "$info" | grep "^URL: " | cut -d " " -f 2`"
 ORIGINAL_PATH="$SVN_PATH"
 SVN_ROOT="`echo "$info" | grep "^Repository Root: " | cut -d " " -f 3`"
}

function set_svn_path()
{
 test "$REVISION" || return
 SVN_PATH="`$HOME/bin/vim/do-find-revision-root $REVISION`"
 ORIGINAL_PATH="$SVN_PATH"
}

function not_found()
{
 echo "**** ERROR: ****"
 echo "Path: $ORIGINAL_PATH"
 test "$NAME" && echo "Name: $NAME"
 test "$REVISION" && echo "Revision: $REVISION"
 echo "SVN Path not found."
 exit 1
}

function step_up()
{
 test "$MODE" = "file" && not_found
 local new_path="`dirname "$SVN_PATH"`"
 test "$new_path" = "$SVN_PATH" && not_found
 SVN_PATH="$new_path"
}

test "$REVISION" && R_REV="-r $REVISION"
test "$REVISION" && C_REV="-c $REVISION"

set_svn_root

case "$COMMAND" in
    blame)
        set_svn_path
        echo "// SVN path: $SVN_PATH"
        echo "// Revision: $REVISION"
        echo
        rev="@"
        test "$ORIGINAL_REVISION" && rev=" -r $ORIGINAL_REVISION"
        test "$R_REV" && rev=" $R_REV"
        $SVN blame "$NAME"$rev 2>&1
    ;;
    change)
        set_svn_path
        while true; do
            $SVN diff $SVN_PATH $C_REV
            test $? = 0 && exit
            step_up
        done
    ;;
    diff)
        set_svn_path
        while true; do
            $SVN diff $SVN_PATH $R_REV
            test $? = 0 && exit
            step_up
        done
    ;;
    local)
        $SVN diff "$NAME" 2>&1
    ;;
    cat)
        $SVN cat "$NAME" -r "$REVISION"
    ;;
    log)
        if test "$NAME"; then
            $SVN log "$NAME" $R_REV
        else
            $SVN log "$SVN_ROOT" $R_REV
        fi
    ;;
    revert)
        set_svn_path
        echo "Path: $SVN_PATH" >&2
        echo "Warning: this operation is irreversible!" >&2
        read -p "Do you want to revert it (yes/no)? " yesno
        test "$yesno" = "yes" || exit 1
        $SVN revert "$NAME" 2>&1
    ;;
    update)
        $SVN up "$NAME" $R_REV
    ;;
    *)
        echo "SVN: Unhandled mode: '$COMMAND'"
        exit 1
    ;;
esac

