#!/bin/bash
#

SVN="`which svn`"

. `dirname $0`/params-parse

function set_svn_root()
{
 local info
 if test "$REVISION"; then
    info="`$SVN info "$NAME" -r $REVISION 2>/dev/null`"
 else
    info="`$SVN info "$NAME" 2>/dev/null`"
 fi
 SVN_PATH="`echo "$info" | grep "^URL: " | cut -d " " -f 2`"
 ORIGINAL_PATH="$SVN_PATH"
 SVN_ROOT="`echo "$info" | grep "^Repository Root: " | cut -d " " -f 3`"
}

function not_found()
{
 echo "**** ERROR: ****"
 echo "Path: $ORIGINAL_PATH"
 test "$NAME" && echo "Name: $NAME"
 test "$REVISION" && echo "Revision: $REVISION"
 echo "SVN Path not found."
 exit 1
}

function step_up()
{
 test "$MODE" = "file" && not_found
 local new_path="`dirname "$SVN_PATH"`"
 test "$new_path" = "$SVN_PATH" && not_found
 SVN_PATH="$new_path"
}

test "$NAME" && set_svn_root

case "$COMMAND" in
    blame)
        echo "// SVN path: $SVN_PATH"
        echo "// Revision: $REVISION"
        echo
        if test "$REVISION"; then
            $SVN blame "$NAME" -r "$REVISION" 2>&1
        else
            $SVN blame "${NAME}@HEAD" 2>&1
        fi
    ;;
    change)
        while true; do
            if test "$REVISION"; then
                if test "$SVN_PATH"; then
                    $SVN diff "$SVN_PATH" -c "$REVISION" 2>&1
                else
                    $SVN diff -c "$REVISION" 2>&1
                fi
            else
                $SVN diff "$SVN_PATH" 2>&1
            fi
            test $? = 0 && exit
            step_up
        done
    ;;
    diff)
        while true; do
            if test "$REVISION"; then
                if test "$SVN_PATH"; then
                    $SVN diff "$SVN_PATH" -r "$REVISION" 2>&1
                else
                    $SVN diff -r "$REVISION" 2>&1
                fi
            else
                $SVN diff "$SVN_PATH" 2>&1
            fi
            test $? = 0 && exit
            step_up
        done
    ;;
    local)
        $SVN diff "$NAME" 2>&1
    ;;
    cat)
        $SVN cat "$NAME" -r "$REVISION"
    ;;
    log)
        if test "$SVN_ROOT"; then
            $SVN log "$SVN_ROOT" -r "$REVISION"
        else
            $SVN log -r "$REVISION"
        fi
    ;;
    revert)
        echo "Path: $SVN_PATH" >&2
        echo "Warning: this operation is irreversible!" >&2
        read -p "Do you want to revert it (yes/no)? " yesno
        test "$yesno" = "yes" || exit 1
        $SVN revert "$NAME" 2>&1
    ;;
    *)
        echo "SVN: Unhandled mode: '$COMMAND'"
        exit 1
    ;;
esac

