#!/bin/bash
#

CTAGS_PARAMS="--recurse=yes --sort=yes --c++-kinds=+p --fields=+iaS --extra=+q"

EXTRA_FILE="tags_extra"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

rm -f tags cscope.*

function find_my_include_dirs()
{
	find -L -maxdepth 1 -mindepth 1 -type d ! -name ".*" ! -name "doc"
	test -f $EXTRA_FILE && grep -v -e "^#" -e "^$" $EXTRA_FILE
}

find_my_include_dirs >cscope.dirs

if test -e extra.dirs
then
	cat extra.dirs | (
		read name
		case ${name:0:1} in
			+)
				echo "${name:1}" >>cscope.dirs
			;;
			-)
				sed -i -e "s%./${name:1}\>%%" cscope.dirs
			;;
		esac
	)
fi

find -L `cat cscope.dirs` -name "*.[ch]" -o -name "*.[ch]pp" -o -name "*.cc" -o -name "*.java" >cscope.files
for pattern in c h cc cpp java
do
	name=`ls *.$pattern 2>/dev/null`
	test "$name" && echo "$name" >>cscope.files 2>/dev/null
done

/usr/bin/ctags $CTAGS_PARAMS -L cscope.files

sed -i -e "s/ /\\\\ /g" cscope.files
/usr/bin/cscope -R -b -q

rm cscope.files cscope.dirs

